[package]
name = "batched"
version = "0.1.0"
edition = "2024"

[dependencies]
batched_derive = { version = "0.1.0", path = "../batched_derive" }

[dev-dependencies]
tokio = { version = "1.44.2", features = ["full"] }
